### PR TITLE
fix event severity change

### LINKED ISSUE #870: Problems panel does not support event severity change
From Zabbix 4.0 there is a possibility to change the severity of the event. This overrides trigger priority. There is a new property "severity" for the [event object ](https://www.zabbix.com/documentation/4.0/manual/api/reference/event/object) in Zabbix:

Severity change of the event does not appier in the problems panel, the alarm is still shown with the default trigger severity. That also impacts trigger filtering by severity: problems with changed severity are still shown in problem panel even if current severity is switched off in options.

If there is a severity in last event of a trigger (new zabbix version) it should be taken for displaying in the problems panel.

### PR DESCRIPTION
**Pull request by memfiz**
This PR closes #870.

- Added a new property "severity" to the ZBXEvent.
- Panel problems for both layouts: show severity from the lastEvent.severity if it exists.
- Create triggerList based on lastEvent.severity if it exists.

Not sure about the code style. It works in my production, but I'm not an expert in typescript/javascript.

### CODE REVIEW

File: src/panel-triggers/components/AlertList/AlertCard.tsx [hunk 1]
```diff
@@ -59,7 +59,13 @@ export default class AlertCard extends PureComponent<AlertCardProps, AlertCardSt
     const showDatasourceName = panelOptions.targets && panelOptions.targets.length > 1;
     const cardClass = classNames('alert-rule-item', 'zbx-trigger-card', { 'zbx-trigger-highlighted': panelOptions.highlightBackground });
     const descriptionClass = classNames('alert-rule-item__text', { 'zbx-description--newline': panelOptions.descriptionAtNewLine });
-    const severityDesc = _.find(panelOptions.triggerSeverity, s => s.priority === Number(problem.priority));
+    
+    let severityDesc: TriggerSeverity;
+    severityDesc = _.find(panelOptions.triggerSeverity, s => s.priority === Number(problem.priority));
+    if (problem.lastEvent.severity) {
```
Comment (alexanderzobnin) [inline src/panel-triggers/components/AlertList/AlertCard.tsx]: It's better to check if `lastEvent` not empty also:
```suggestion
    if (problem.lastEvent && problem.lastEvent.severity) {
```

File: src/panel-triggers/components/Problems/Problems.tsx [hunk 2]
```diff
@@ -179,7 +179,13 @@ export default class ProblemList extends PureComponent<ProblemListProps, Problem
 function SeverityCell(props: RTCell<ZBXTrigger>, problemSeverityDesc: TriggerSeverity[], markAckEvents?: boolean, ackEventColor?: string) {
   const problem = props.original;
   let color: string;
-  const severityDesc = _.find(problemSeverityDesc, s => s.priority === Number(props.original.priority));
+  
+  let severityDesc: TriggerSeverity;
+  severityDesc = _.find(problemSeverityDesc, s => s.priority === Number(props.original.priority));
+  if (problem.lastEvent.severity) {
```
Comment (alexanderzobnin) [inline src/panel-triggers/components/Problems/Problems.tsx]: The same as above.

File: src/panel-triggers/triggers_panel_ctrl.js [hunk 3]
```diff
@@ -398,7 +398,12 @@ export class TriggerPanelCtrl extends PanelCtrl {
 
     // Filter triggers by severity
     triggerList = _.filter(triggerList, trigger => {
-      return this.panel.triggerSeverity[trigger.priority].show;
+      //return this.panel.triggerSeverity[trigger.priority].show;
+      if (trigger.lastEvent.severity) {
```
Comment (alexanderzobnin) [inline src/panel-triggers/triggers_panel_ctrl.js]: The same
```suggestion
      if (trigger.lastEvent && trigger.lastEvent.severity) {
```

File: src/panel-triggers/triggers_panel_ctrl.js [hunk 4]
```diff
@@ -398,7 +398,12 @@ export class TriggerPanelCtrl extends PanelCtrl {
 
     // Filter triggers by severity
     triggerList = _.filter(triggerList, trigger => {
-      return this.panel.triggerSeverity[trigger.priority].show;
+      //return this.panel.triggerSeverity[trigger.priority].show;
```
Comment (alexanderzobnin) [inline src/panel-triggers/triggers_panel_ctrl.js]: Could be removed
```suggestion
```

**Comment by alexanderzobnin** [comment]
@memfiz could you fix comments above?

**Comment by memfiz** [comment]
> @memfiz could you fix comments above?

Fixed.

**Comment by alexanderzobnin** [comment]
@memfiz I mean `trigger.lastEvent.severity` (https://github.com/alexanderzobnin/grafana-zabbix/pull/872#discussion_r367253270)

**Comment by memfiz** [comment]
Yes, my fault. Another try...
